# Running as root is safe: this is a development lab image, not production.
FROM rabbitmq@sha256:a762c02d0c1fa7c3de1eca5d62b4fe9812649f41a3b38d716e1afcbe7e5387ad

COPY enabled_plugins.no-plugin /etc/rabbitmq/enabled_plugins
