loopback_users.guest = false

listeners.tcp.default = 5672

management.listener.ip = 0.0.0.0
management.listener.port = 15672

prometheus.tcp.port = 15692
prometheus.return_per_object_metrics = true

cluster_partition_handling = pause_minority

disk_free_limit.absolute = 512MB

log.console = true
log.console.level = info

quorum_queue.commands_soft_limit = 256

definitions.import_backend = local_filesystem
definitions.local.path = /etc/rabbitmq/definitions.json
