sonar.projectKey=Goopil_php-rabbit-rs
sonar.organization=goopil

sonar.sources=crates/rabbit-rs-core/src,crates/rabbit-rs-php/src,packages/laravel-queue/src
sonar.tests=crates/rabbit-rs-core/tests,crates/rabbit-rs-php/tests,packages/laravel-queue/tests

sonar.coverage.exclusions=**/tests/**,benchmarks/**,scripts/**,target/**
sonar.test.exclusions=**/tests/**,benchmarks/**,scripts/**,target/**
sonar.cpd.exclusions=**/tests/**

sonar.links.homepage=https://github.com/Goopil/php-rabbit-rs
sonar.links.scm=https://github.com/Goopil/php-rabbit-rs
sonar.links.issue=https://github.com/Goopil/php-rabbit-rs/issues
