[target.'cfg(target_os = "macos")']
rustflags = [
    "-C", "link-arg=-Wl,-undefined,dynamic_lookup",
    "-C", "link-arg=-mmacosx-version-min=11.0"
]

[target.'cfg(target_os = "linux")']
rustflags = []

[target.'cfg(target_os = "windows")']
rustflags = [
    "-C", "link-arg=-Wl,--out-implib=ext/first_tery.lib"
]
